#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias -s py=vim
alias -s conf=vim
alias -s js=vim
alias -s php=vim
alias svim="sudo vim"

export PIP_DOWNLOAD_CACHE=~/.pip_downloads
